# Generated by Django 5.2.6 on 2025-09-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Nom')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('isDone', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'todo',
                'verbose_name_plural': 'todo',
                'ordering': ('name', 'description', 'isDone'),
            },
        ),
    ]
