# Generated by Django 5.2.6 on 2025-09-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Nom')),
                ('color', models.CharField(max_length=6, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categorie',
                'ordering': ('id', 'name', 'color'),
            },
        ),
    ]
