# Generated by Django 5.2.6 on 2025-09-17 15:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todo_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id', 'name', 'color', 'background_color'), 'verbose_name': 'categorie', 'verbose_name_plural': 'categorie'},
        ),
        migrations.AddField(
            model_name='category',
            name='background_color',
            field=colorfield.fields.ColorField(default='', image_field=None, max_length=25, samples=None),
        ),
    ]
