# Generated by Django 5.2.6 on 2025-09-17 15:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_category_options_category_background_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id', 'name', 'color', 'backgroundColor'), 'verbose_name': 'categorie', 'verbose_name_plural': 'categorie'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='background_color',
        ),
        migrations.AddField(
            model_name='category',
            name='backgroundColor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
