# Generated by Django 5.2.6 on 2025-09-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('id', 'name', 'description', 'isDone'), 'verbose_name': 'todo', 'verbose_name_plural': 'todo'},
        ),
    ]
