# Generated by Django 5.2.6 on 2025-09-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id', 'name', 'color'), 'verbose_name': 'categorie', 'verbose_name_plural': 'categorie'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='backgroundColor',
        ),
    ]
