# Generated by Django 5.2.6 on 2025-10-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50, verbose_name='Prenom')),
                ('lastName', models.CharField(max_length=50, verbose_name='Nom')),
                ('profilePicture', models.CharField(max_length=150, verbose_name='ProfilePicture')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'ordering': ('id', 'firstName', 'lastName', 'profilePicture'),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='todo_app.user'),
        ),
    ]
