# Generated by Django 5.2.6 on 2025-10-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_user_category_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(upload_to=''),
        ),
    ]
